# Generated by Django 6.0.6 on 2026-07-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(0, 'Superadmin'), (1, 'Admin'), (2, 'Voter')], default=2, max_length=1),
        ),
    ]
